sudo: false

language: php

php:
    - 7.1
    - 7.2

install:
    - composer install

script:
    - composer test-coverage
    - composer cs-check
    - composer license-check

after_success:
    - composer upload-coverage
